**Load and Inspect Data:**

In [12]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
clubs_df = pd.read_csv('/content/clubs.csv')

In [3]:
# Check the first few rows of the datasets
clubs_df.head()

,id,club,season,matches_played,wins,draws,losses,goals_scored,goals_conceded,goal_difference,...,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,last_season,filename,url,club_standardized_y
0,1,Bayern Munich,2022-23,34,21,8,5,92,38,54,...,57.7,17,Allianz Arena,75000,€-64.65m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/fc-bayern-munc...,fc bayern münchen
1,2,Borussia Dortmund,2022-23,34,22,5,7,83,44,39,...,50.0,18,SIGNAL IDUNA PARK,81365,€-30.60m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/borussia-dortm...,borussia dortmund
2,3,RB Leipzig,2022-23,34,20,6,8,64,41,23,...,73.1,17,Red Bull Arena,47069,€-21.50m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/rasenballsport...,rasenballsport leipzig
3,4,Union Berlin,2022-23,34,18,8,8,51,38,13,...,55.6,6,Stadion An der Alten Försterei,22012,+€5.80m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/1-fc-union-ber...,1. fußballclub union berlin
4,5,SC Freiburg,2022-23,34,17,8,9,51,44,7,...,44.4,6,Europa-Park Stadion,34700,€-7.10m,NaN,2024,../data/raw/transfermarkt-scraper/2024/clubs.j...,https://www.transfermarkt.co.uk/sc-freiburg/st...,sport-club freiburg

In [4]:
print("🔹 Info générales sur les données :")
display(clubs_df.info())

🔹 Info générales sur les données :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 49 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       116 non-null    int64
 1   club                     116 non-null    object
 2   season                   116 non-null    object
 3   matches_played           116 non-null    int64
 4   wins                     116 non-null    int64
 5   draws                    116 non-null    int64
 6   losses                   116 non-null    int64
 7   goals_scored             116 non-null    int64
 8   goals_conceded           116 non-null    int64
 9   goal_difference          116 non-null    int64
 10  points                   116 non-null    int64
 11  top_scorer               116 non-null    object
 12  clean_sheets             116 non-null    int64
 13  possession (%)           116 non-null    float64
 14  pass_accuracy (%)        116 non-null    float64
 15  shots_per_match          116 non-null    float64
 16  fouls_committed          116 non-null    int64
 17  yellow_cards             116 non-null    int64
 18  red_cards                116 non-null    float64
 19  total_injuries           116 non-null    int64
 20  recruited_players        116 non-null    int64
 21  total_attacks_left       116 non-null    int64
 22  total_attacks_middle     116 non-null    int64
 23  total_attacks_right      116 non-null    int64
 24  conceded_attacks_left    116 non-null    float64
 25  conceded_attacks_middle  116 non-null    int64
 26  conceded_attacks_right   116 non-null    int64
 27  league                   116 non-null    object
 28  possession(%)            116 non-null    float64
 29  club_standardized_x      116 non-null    object
 30  matched_club             116 non-null    object
 31  club_id                  116 non-null    int64
 32  club_code                116 non-null    object
 33  name                     116 non-null    object
 34  domestic_competition_id  116 non-null    object
 35  total_market_value       0 non-null      float64
 36  squad_size               116 non-null    int64
 37  average_age              115 non-null    float64
 38  foreigners_number        116 non-null    int64
 39  foreigners_percentage    115 non-null    float64
 40  national_team_players    116 non-null    int64
 41  stadium_name             116 non-null    object
 42  stadium_seats            116 non-null    int64
 43  net_transfer_record      116 non-null    object
 44  coach_name               0 non-null      float64
 45  last_season              116 non-null    int64
 46  filename                 116 non-null    object
 47  url                      116 non-null    object
 48  club_standardized_y      116 non-null    object
dtypes: float64(10), int64(25), object(14)
memory usage: 44.5+ KB

None

In [5]:
display(clubs_df.describe())

,id,matches_played,wins,draws,losses,goals_scored,goals_conceded,goal_difference,points,clean_sheets,...,club_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_seats,coach_name,last_season
count,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,...,116.000000,0.0,116.000000,115.000000,116.000000,115.000000,116.000000,116.000000,0.0,116.000000
mean,10.189655,36.758621,13.879310,8.974138,13.905172,51.568966,51.646552,-0.077586,50.525862,9.094828,...,1141.620690,NaN,26.577586,26.045217,14.568966,54.526087,9.163793,35522.362069,NaN,2023.551724
std,5.636702,1.858567,6.156164,2.662007,5.408493,15.936954,13.001173,26.069523,17.326763,4.556846,...,2629.483995,NaN,4.047868,1.605268,5.730504,19.318522,5.477137,19309.767574,NaN,1.307802
min,1.000000,34.000000,3.000000,3.000000,2.000000,23.000000,20.000000,-51.000000,17.000000,1.000000,...,3.000000,NaN,0.000000,21.300000,0.000000,4.200000,0.000000,4400.000000,NaN,2013.000000
25%,5.000000,34.000000,10.000000,7.000000,10.000000,40.000000,42.000000,-17.000000,37.750000,6.000000,...,195.000000,NaN,25.000000,25.000000,11.000000,41.200000,5.000000,21005.250000,NaN,2024.000000
50%,10.000000,38.000000,13.000000,9.000000,14.000000,49.000000,50.000000,-3.000000,49.000000,8.000000,...,483.500000,NaN,26.000000,26.100000,15.000000,56.700000,9.000000,31216.500000,NaN,2024.000000
75%,15.000000,38.000000,18.250000,11.000000,18.000000,61.000000,62.000000,18.000000,63.250000,12.000000,...,1028.250000,NaN,28.000000,27.200000,18.000000,69.400000,13.000000,49572.500000,NaN,2024.000000
max,20.000000,38.000000,28.000000,15.000000,28.000000,94.000000,81.000000,61.000000,90.000000,26.000000,...,23826.000000,NaN,36.000000,29.900000,29.000000,100.000000,22.000000,81365.000000,NaN,2024.000000

**Data Cleaning:**

In [7]:
nan_counts = clubs_df.isna().sum().sum()
# Display the result
print(nan_counts)

234

In [8]:
# Display columns with missing values in the clubs dataset
missing_club_data = clubs_df.isna().sum()
print("🔹 Missing Data in Clubs Dataset:")
print(missing_club_data[missing_club_data > 0])

🔹 Missing Data in Clubs Dataset:
total_market_value       116
average_age                1
foreigners_percentage      1
coach_name               116
dtype: int64

In [9]:
# Drop the 'total_market_value' column
clubs_df = clubs_df.drop(columns=['total_market_value','coach_name','club_standardized_y','url','filename'])
# Impute missing values in clubs dataset
clubs_df['average_age'] = clubs_df['average_age'].fillna(clubs_df['average_age'].mean())
clubs_df['foreigners_percentage'] = clubs_df['foreigners_percentage'].fillna(clubs_df['foreigners_percentage'].mean())

# Verify the result
missing_club_data_after = clubs_df.isna().sum()
print("🔹 Missing Data in Clubs Dataset After Imputation:")
print(missing_club_data_after[missing_club_data_after > 0])

🔹 Missing Data in Clubs Dataset After Imputation:
Series([], dtype: int64)

**Data Transformation:**

In [11]:
# Select columns with object or category data types (categorical columns)
categorical_columns = clubs_df.select_dtypes(include=['object', 'category'])

print(clubs_df.columns.tolist())

# Display the names of categorical columns
print(categorical_columns.columns.tolist())

['id', 'club', 'season', 'matches_played', 'wins', 'draws', 'losses', 'goals_scored', 'goals_conceded', 'goal_difference', 'points', 'top_scorer', 'clean_sheets', 'possession (%)', 'pass_accuracy (%)', 'shots_per_match', 'fouls_committed', 'yellow_cards', 'red_cards', 'total_injuries', 'recruited_players', 'total_attacks_left', 'total_attacks_middle', 'total_attacks_right', 'conceded_attacks_left', 'conceded_attacks_middle', 'conceded_attacks_right', 'league', 'possession(%)', 'club_standardized_x', 'matched_club', 'club_id', 'club_code', 'name', 'domestic_competition_id', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'national_team_players', 'stadium_name', 'stadium_seats', 'net_transfer_record', 'last_season']
['club', 'season', 'top_scorer', 'league', 'club_standardized_x', 'matched_club', 'club_code', 'name', 'domestic_competition_id', 'stadium_name', 'net_transfer_record']

In [13]:
# List of categorical columns to encode in clubs_df, excluding 'club' because it needs to be retained as-is
categorical_columns_club = ['season', 'top_scorer', 'league', 'club_standardized_x',
                            'matched_club', 'club_code', 'name', 'domestic_competition_id',
                            'stadium_name']

# Initialize LabelEncoder
label_encoder_club = LabelEncoder()

# Loop through each categorical column in clubs_df, apply Label Encoding, and replace the original column with the encoded values
for col in categorical_columns_club:
    if col in clubs_df.columns:
        # Apply Label Encoding to each categorical column and replace the original column with the encoded values
        clubs_df[col] = label_encoder_club.fit_transform(clubs_df[col])

        # Display the mapping for the column
        print(f"\nMapping for '{col}' column:")
        label_mapping = dict(zip(label_encoder_club.classes_, range(len(label_encoder_club.classes_))))  # Clean mapping
        print(label_mapping)

Mapping for 'season' column:
{'2022-23': 0}

Mapping for 'top_scorer' column:
{'Ademola Lookman (13)': 0, 'Adrien Hunou (6)': 1, 'Aleksandar Mitrović (14)': 2, 'Alexander Sørloth (12)': 3, 'Alexandre Lacazette (27)': 4, 'Alexis Mac Allister (10)': 5, 'Alexis Sánchez (14)': 6, 'Amine Gouiri (12)': 7, 'Anastasios Douvikas (12)': 8, 'Andrej Kramari? (12)': 9, 'Ante Budimir (8)': 10, 'Antoine Griezmann (15)': 11, 'Antonio Sanabria (8)': 12, 'Arthur Cabral (7)': 13, 'Beto (10)': 14, 'Borja Iglesias (15)': 15, 'Boulaye Dia (16)': 16, 'Burak Yılmaz (8)': 17, 'Callum Wilson (18)': 18, 'Christopher Nkunku (16)': 19, 'Ciro Immobile (12)': 20, 'Cristhian Stuani (9)': 21, 'Cyle Larin (8)': 22, 'Cyriel Dessers (7)': 23, 'Cyril Ngonge (5)': 24, 'Daniel Podence (6)': 25, 'Davie Selke (8)': 26, 'Dodi Lukebakio (11)': 27, 'Domenico Berardi (11)': 28, 'Dominic Solanke (6)': 29, 'Dusan Tadić (14)': 30, 'Dušan Vlahović (10)': 31, 'Dwight McNeil (7)': 32, 'Eberechi Eze (10)': 33, 'El Bilal Touré (7)': 34, 'Elye Wahi (19)': 35, 'Enes Ünal (14)': 36, 'Eric Maxim Choupo-Moting (17)': 37, 'Erling Haaland (36)': 38, 'Ermedin Demirovi? (9)': 39, 'Folarin Balogun (21)': 40, 'Franck Honorat (7)': 41, 'Gabriel Strefezza (8)': 42, 'Gaëtan Laborde (9)': 43, 'Gerard Moreno (10)': 44, 'Gianluca Caprari (7)': 45, 'Habib Diallo (20)': 46, 'Harry Kane (30)': 47, 'Iago Aspas (12)': 48, 'Isi Palazón (7)': 49, 'Ivan Toney (20)': 50, 'Iñaki Williams (10)': 51, 'James Maddison (10)': 52, 'James Ward-Prowse (9)': 53, 'Jonas Wind (9)': 54, 'Jonathan David (24)': 55, 'Joselu (16)': 56, 'Justin Kluivert (6)': 57, 'Kai Havertz (7)': 58, 'Karim Benzema (19)': 59, 'Karim Onisiwo (10)': 60, 'Kylian Mbappé (29)': 61, 'Lautaro Martínez (21)': 62, 'Lois Openda (12)': 63, 'Loïs Openda (21)': 64, 'Ludovic Blas (7)': 65, "M'Bala Nzola (13)": 66, "M'Baye Niang (6)": 67, 'Magnus Mattsson (7)': 68, 'Mama Baldé (8)': 69, 'Manolo Gabbiadini (4)': 70, 'Marcus Rashford (17)': 71, 'Marcus Thuram (13)': 72, 'Marius Bülter (8)': 73, 'Marko Arnautović (10)': 74, 'Martin Ødegaard (15)': 75, 'Michail Antonio (9)': 76, 'Michiel Kramer (9)': 77, 'Mitchel Paulissen (4)': 78, 'Mohamed Salah (19)': 79, 'Mounaïm El Idrissy (5)': 80, 'Moussa Diaby (9)': 81, 'Muhammed Cham (7)': 82, 'Niclas Füllkrug (16)': 83, 'Olivier Giroud (13)': 84, 'Ollie Watkins (15)': 85, 'Paulo Dybala (12)': 86, 'Pere Milla (6)': 87, 'Philipp Hofmann (8)': 88, 'Randal Kolo Muani (15)': 89, 'Reda Kharchouch (5)': 90, 'Ricardo Pepi (7)': 91, 'Richairo Živković (6)': 92, 'Ricky van Wolfswinkel (16)': 93, 'Robert Lewandowski (23)': 94, 'Robert Mühren (10)': 95, 'Rodrigo (13)': 96, 'Santiago Giménez (15)': 97, 'Serhou Guirassy (11)': 98, 'Sheraldo Becker (11)': 99, 'Sydney van Hooijdonk (10)': 100, 'Sébastien Haller (9)': 101, 'Taiwo Awoniyi (10)': 102, 'Terem Moffi (14)': 103, 'Thijs Dallinga (12)': 104, 'Tobias Lauritsen (12)': 105, 'Tommaso Baldanzi (6)': 106, 'Vangelis Pavlidis (16)': 107, 'Vedat Muriqi (15)': 108, 'Victor Osimhen (26)': 109, 'Vincenzo Grifo (13)': 110, 'Willum Þór Willumsson (8)': 111, 'Wissam Ben Yedder (19)': 112, 'Xavi Simons (19)': 113, 'Youssef En-Nesyri (8)': 114, 'Álvaro Negredo (7)': 115}

Mapping for 'league' column:
{'Bundesliga': 0, 'Eredivisie': 1, 'La Liga': 2, 'Ligue 1': 3, 'Premier League': 4, 'Serie A': 5}

Mapping for 'club_standardized_x' column:
{'ac milan': 0, 'ajaccio': 1, 'ajax': 2, 'almería': 3, 'angers': 4, 'arsenal': 5, 'as roma': 6, 'aston villa': 7, 'atalanta': 8, 'athletic bilbao': 9, 'atlético madrid': 10, 'augsburg': 11, 'auxerre': 12, 'az alkmaar': 13, 'barcelona': 14, 'bayer leverkusen': 15, 'bayern munich': 16, 'bologna': 17, 'borussia dortmund': 18, 'borussia mönchengladbach': 19, 'bournemouth': 20, 'brentford': 21, 'brest': 22, 'brighton': 23, 'celta vigo': 24, 'chelsea': 25, 'clermont foot': 26, 'cremonese': 27, 'crystal palace': 28, 'cádiz': 29, 'eintracht frankfurt': 30, 'elche': 31, 'empoli': 32, 'espanyol': 33, 'everton': 34, 'excelsior': 35, 'fc emmen': 36, 'fc groningen': 37, 'fc köln': 38, 'fc twente': 39, 'fc utrecht': 40, 'fc volendam': 41, 'feyenoord': 42, 'fiorentina': 43, 'fortuna sittard': 44, 'fulham': 45, 'getafe': 46, 'girona': 47, 'go ahead eagles': 48, 'hellas verona': 49, 'hertha berlin': 50, 'hoffenheim': 51, 'inter milan': 52, 'juventus': 53, 'lazio': 54, 'lecce': 55, 'leeds united': 56, 'leicester city': 57, 'lens': 58, 'lille': 59, 'liverpool': 60, 'lorient': 61, 'lyon': 62, 'mainz 05': 63, 'mallorca': 64, 'manchester city': 65, 'manchester united': 66, 'marseille': 67, 'monaco': 68, 'montpellier': 69, 'monza': 70, 'nantes': 71, 'napoli': 72, 'nec nijmegen': 73, 'newcastle united': 74, 'nice': 75, 'nottingham forest': 76, 'osasuna': 77, 'paris saint-germain': 78, 'psv eindhoven': 79, 'rayo vallecano': 80, 'rb leipzig': 81, 'real betis': 82, 'real madrid': 83, 'real sociedad': 84, 'reims': 85, 'rennes': 86, 'rkc waalwijk': 87, 'salernitana': 88, 'sampdoria': 89, 'sassuolo': 90, 'sc cambuur': 91, 'sc freiburg': 92, 'sc heerenveen': 93, 'schalke 04': 94, 'sevilla': 95, 'southampton': 96, 'sparta rotterdam': 97, 'spezia': 98, 'strasbourg': 99, 'stuttgart': 100, 'torino': 101, 'tottenham hotspur': 102, 'toulouse': 103, 'troyes': 104, 'udinese': 105, 'union berlin': 106, 'valencia': 107, 'valladolid': 108, 'vfl bochum': 109, 'villarreal': 110, 'vitesse': 111, 'werder bremen': 112, 'west ham united': 113, 'wolfsburg': 114, 'wolverhampton': 115}

Mapping for 'matched_club' column:
{'1. Fußball- und Sportverein Mainz 05': 0, '1. Fußballclub Union Berlin': 1, '1.FC Köln': 2, 'AC Ajaccio': 3, 'AFC Ajax Amsterdam': 4, 'Alkmaar Zaanstreek': 5, 'Arsenal Tula': 6, 'Association Football Club Bournemouth': 7, 'Association de la Jeunesse auxerroise': 8, 'Association sportive de Monaco Football Club': 9, 'Associazione Calcio Fiorentina': 10, 'Associazione Calcio Monza': 11, 'Associazione Sportiva Roma': 12, 'Aston Villa Football Club': 13, 'Atalanta Bergamasca Calcio S.p.a.': 14, 'Athletic Club Bilbao': 15, 'Bayer 04 Leverkusen Fußball': 16, 'Bologna Football Club 1909': 17, 'Borussia Dortmund': 18, 'Borussia Verein für Leibesübungen 1900 Mönchengladbach': 19, 'Brentford Football Club': 20, 'Brighton and Hove Albion Football Club': 21, 'Chelsea Football Club': 22, 'Chievo Verona': 23, 'Clermont Foot 63': 24, 'Club Atlético Osasuna': 25, 'Club Atlético de Madrid S.A.D.': 26, 'Crystal Palace Football Club': 27, 'Cádiz CF': 28, 'ESTAC Troyes': 29, 'Eindhovense Voetbalvereniging Philips Sport Vereniging': 30, 'Eintracht Frankfurt Fußball AG': 31, 'Elche CF': 32, 'Empoli Football Club S.r.l.': 33, 'Everton Football Club': 34, 'Excelsior Rotterdam': 35, 'FC Bayern München': 36, 'FC Emmen': 37, 'FC Lorient': 38, 'FC Schalke 04': 39, 'FC Volendam': 40, 'Feyenoord Rotterdam': 41, 'Football Club Groningen': 42, 'Football Club Internazionale Milano S.p.A.': 43, 'Football Club Twente': 44, 'Football Club Utrecht': 45, 'Football Club de Nantes': 46, 'Fortuna Sittardia Combinatie': 47, 'Fulham Football Club': 48, 'Futbol Club Barcelona': 49, 'Fußball-Club Augsburg 1907': 50, 'Getafe Club de Fútbol S.A.D. Team Dubai': 51, 'Girona Fútbol Club S. A. D.': 52, 'Go Ahead Eagles': 53, 'Hertha BSC': 54, 'Juventus Football Club': 55, 'Leeds United': 56, 'Leicester City Football Club': 57, 'Lille Olympique Sporting Club': 58, 'Liverpool Football Club': 59, 'Manchester City Football Club': 60, 'Manchester United Football Club': 61, 'Montpellier Hérault Sport Club': 62, 'Newcastle United Football Club': 63, 'Nijmegen Eendracht Combinatie': 64, 'Nottingham Forest Football Club': 65, "Olympique Gymnaste Club Nice Côte d'Azur": 66, 'Olympique Lyonnais': 67, 'Olympique de Marseille': 68, 'Paris Saint-Germain Football Club': 69, 'Racing Club de Lens': 70, 'Racing Club de Strasbourg Alsace': 71, 'Rangers Football Club': 72, 'RasenBallsport Leipzig': 73, 'Rayo Vallecano de Madrid S.A.D.': 74, 'Real Betis Balompié S.A.D.': 75, 'Real Club Celta de Vigo S. A. D.': 76, 'Real Club Deportivo Mallorca S.A.D.': 77, 'Real Madrid Club de Fútbol': 78, 'Real Sociedad de Fútbol S.A.D.': 79, 'Real Valladolid Club de Fútbol S.A.D.': 80, 'Reial Club Deportiu Espanyol de Barcelona S.A.D.': 81, 'Rooms Katholieke Combinatie Waalwijk': 82, 'SC Cambuur Leeuwarden': 83, 'Sevilla Fútbol Club S.A.D.': 84, 'Società Sportiva Calcio Napoli': 85, 'Società Sportiva Lazio S.p.A.': 86, 'Southampton Football Club': 87, 'Sparta Rotterdam': 88, 'Spezia Calcio': 89, 'Sport-Club Freiburg': 90, 'Sportclub Heerenveen': 91, 'Sportverein Werder Bremen von 1899': 92, 'Stade brestois 29': 93, 'Stade de Reims': 94, 'Torino Calcio': 95, 'Tottenham Hotspur Football Club': 96, 'Toulouse Football Club': 97, 'Turn- und Sportgemeinschaft 1899 Hoffenheim Fußball-Spielbetriebs': 98, 'UC Sampdoria': 99, 'UD Almería': 100, 'US Cremonese': 101, 'US Salernitana 1919': 102, 'US Sassuolo': 103, 'Udinese Calcio': 104, 'Unione Sportiva Lecce': 105, 'Valencia Club de Fútbol S. A. D.': 106, 'Valenciennes FC': 107, 'Verein für Bewegungsspiele Stuttgart 1893': 108, 'Verein für Leibesübungen Bochum 1848 Fußballgemeinschaft': 109, 'Verein für Leibesübungen Wolfsburg': 110, 'Villarreal Club de Fútbol S.A.D.': 111, 'Vitesse Arnhem': 112, 'West Ham United Football Club': 113, 'Wolverhampton Wanderers Football Club': 114}

Mapping for 'club_code' column:
{'1-fc-koln': 0, '1-fc-union-berlin': 1, '1-fsv-mainz-05': 2, 'ac-ajaccio': 3, 'ac-florenz': 4, 'ac-monza': 5, 'afc-bournemouth': 6, 'aj-auxerre': 7, 'ajax-amsterdam': 8, 'arsenal-tula': 9, 'as-monaco': 10, 'as-rom': 11, 'aston-villa': 12, 'atalanta-bergamo': 13, 'athletic-bilbao': 14, 'atletico-madrid': 15, 'az-alkmaar': 16, 'bayer-04-leverkusen': 17, 'borussia-dortmund': 18, 'borussia-monchengladbach': 19, 'brighton-amp-hove-albion': 20, 'ca-osasuna': 21, 'celta-vigo': 22, 'chievo-verona': 23, 'clermont-foot-63': 24, 'crystal-palace': 25, 'eintracht-frankfurt': 26, 'es-troyes-ac': 27, 'espanyol-barcelona': 28, 'fc-augsburg': 29, 'fc-barcelona': 30, 'fc-bayern-munchen': 31, 'fc-bologna': 32, 'fc-brentford': 33, 'fc-cadiz': 34, 'fc-chelsea': 35, 'fc-elche': 36, 'fc-emmen': 37, 'fc-empoli': 38, 'fc-everton': 39, 'fc-fulham': 40, 'fc-getafe': 41, 'fc-girona': 42, 'fc-groningen': 43, 'fc-liverpool': 44, 'fc-lorient': 45, 'fc-nantes': 46, 'fc-paris-saint-germain': 47, 'fc-schalke-04': 48, 'fc-sevilla': 49, 'fc-southampton': 50, 'fc-toulouse': 51, 'fc-turin': 52, 'fc-twente-enschede': 53, 'fc-utrecht': 54, 'fc-valencia': 55, 'fc-valenciennes': 56, 'fc-villarreal': 57, 'fc-volendam': 58, 'feyenoord-rotterdam': 59, 'fortuna-sittard': 60, 'glasgow-rangers': 61, 'go-ahead-eagles-deventer': 62, 'hertha-bsc': 63, 'inter-mailand': 64, 'juventus-turin': 65, 'lazio-rom': 66, 'leeds-united': 67, 'leicester-city': 68, 'losc-lille': 69, 'manchester-city': 70, 'manchester-united': 71, 'montpellier-hsc': 72, 'nec-nijmegen': 73, 'newcastle-united': 74, 'nottingham-forest': 75, 'ogc-nizza': 76, 'olympique-lyon': 77, 'olympique-marseille': 78, 'psv-eindhoven': 79, 'rasenballsport-leipzig': 80, 'rayo-vallecano': 81, 'rc-lens': 82, 'rc-strassburg-alsace': 83, 'rcd-mallorca': 84, 'real-betis-sevilla': 85, 'real-madrid': 86, 'real-sociedad-san-sebastian': 87, 'real-valladolid': 88, 'rkc-waalwijk': 89, 'sampdoria-genua': 90, 'sbv-excelsior-rotterdam': 91, 'sc-cambuur-leeuwarden': 92, 'sc-freiburg': 93, 'sc-heerenveen': 94, 'sparta-rotterdam': 95, 'spezia-calcio': 96, 'ssc-neapel': 97, 'stade-brest-29': 98, 'stade-reims': 99, 'sv-werder-bremen': 100, 'tottenham-hotspur': 101, 'tsg-1899-hoffenheim': 102, 'ud-almeria': 103, 'udinese-calcio': 104, 'us-cremonese': 105, 'us-lecce': 106, 'us-salernitana-1919': 107, 'us-sassuolo': 108, 'vfb-stuttgart': 109, 'vfl-bochum': 110, 'vfl-wolfsburg': 111, 'vitesse-arnheim': 112, 'west-ham-united': 113, 'wolverhampton-wanderers': 114}

Mapping for 'name' column:
{'1. Fußball- und Sportverein Mainz 05': 0, '1. Fußballclub Union Berlin': 1, '1.FC Köln': 2, 'AC Ajaccio': 3, 'AFC Ajax Amsterdam': 4, 'Alkmaar Zaanstreek': 5, 'Arsenal Tula': 6, 'Association Football Club Bournemouth': 7, 'Association de la Jeunesse auxerroise': 8, 'Association sportive de Monaco Football Club': 9, 'Associazione Calcio Fiorentina': 10, 'Associazione Calcio Monza': 11, 'Associazione Sportiva Roma': 12, 'Aston Villa Football Club': 13, 'Atalanta Bergamasca Calcio S.p.a.': 14, 'Athletic Club Bilbao': 15, 'Bayer 04 Leverkusen Fußball': 16, 'Bologna Football Club 1909': 17, 'Borussia Dortmund': 18, 'Borussia Verein für Leibesübungen 1900 Mönchengladbach': 19, 'Brentford Football Club': 20, 'Brighton and Hove Albion Football Club': 21, 'Chelsea Football Club': 22, 'Chievo Verona': 23, 'Clermont Foot 63': 24, 'Club Atlético Osasuna': 25, 'Club Atlético de Madrid S.A.D.': 26, 'Crystal Palace Football Club': 27, 'Cádiz CF': 28, 'ESTAC Troyes': 29, 'Eindhovense Voetbalvereniging Philips Sport Vereniging': 30, 'Eintracht Frankfurt Fußball AG': 31, 'Elche CF': 32, 'Empoli Football Club S.r.l.': 33, 'Everton Football Club': 34, 'Excelsior Rotterdam': 35, 'FC Bayern München': 36, 'FC Emmen': 37, 'FC Lorient': 38, 'FC Schalke 04': 39, 'FC Volendam': 40, 'Feyenoord Rotterdam': 41, 'Football Club Groningen': 42, 'Football Club Internazionale Milano S.p.A.': 43, 'Football Club Twente': 44, 'Football Club Utrecht': 45, 'Football Club de Nantes': 46, 'Fortuna Sittardia Combinatie': 47, 'Fulham Football Club': 48, 'Futbol Club Barcelona': 49, 'Fußball-Club Augsburg 1907': 50, 'Getafe Club de Fútbol S.A.D. Team Dubai': 51, 'Girona Fútbol Club S. A. D.': 52, 'Go Ahead Eagles': 53, 'Hertha BSC': 54, 'Juventus Football Club': 55, 'Leeds United': 56, 'Leicester City Football Club': 57, 'Lille Olympique Sporting Club': 58, 'Liverpool Football Club': 59, 'Manchester City Football Club': 60, 'Manchester United Football Club': 61, 'Montpellier Hérault Sport Club': 62, 'Newcastle United Football Club': 63, 'Nijmegen Eendracht Combinatie': 64, 'Nottingham Forest Football Club': 65, "Olympique Gymnaste Club Nice Côte d'Azur": 66, 'Olympique Lyonnais': 67, 'Olympique de Marseille': 68, 'Paris Saint-Germain Football Club': 69, 'Racing Club de Lens': 70, 'Racing Club de Strasbourg Alsace': 71, 'Rangers Football Club': 72, 'RasenBallsport Leipzig': 73, 'Rayo Vallecano de Madrid S.A.D.': 74, 'Real Betis Balompié S.A.D.': 75, 'Real Club Celta de Vigo S. A. D.': 76, 'Real Club Deportivo Mallorca S.A.D.': 77, 'Real Madrid Club de Fútbol': 78, 'Real Sociedad de Fútbol S.A.D.': 79, 'Real Valladolid Club de Fútbol S.A.D.': 80, 'Reial Club Deportiu Espanyol de Barcelona S.A.D.': 81, 'Rooms Katholieke Combinatie Waalwijk': 82, 'SC Cambuur Leeuwarden': 83, 'Sevilla Fútbol Club S.A.D.': 84, 'Società Sportiva Calcio Napoli': 85, 'Società Sportiva Lazio S.p.A.': 86, 'Southampton Football Club': 87, 'Sparta Rotterdam': 88, 'Spezia Calcio': 89, 'Sport-Club Freiburg': 90, 'Sportclub Heerenveen': 91, 'Sportverein Werder Bremen von 1899': 92, 'Stade brestois 29': 93, 'Stade de Reims': 94, 'Torino Calcio': 95, 'Tottenham Hotspur Football Club': 96, 'Toulouse Football Club': 97, 'Turn- und Sportgemeinschaft 1899 Hoffenheim Fußball-Spielbetriebs': 98, 'UC Sampdoria': 99, 'UD Almería': 100, 'US Cremonese': 101, 'US Salernitana 1919': 102, 'US Sassuolo': 103, 'Udinese Calcio': 104, 'Unione Sportiva Lecce': 105, 'Valencia Club de Fútbol S. A. D.': 106, 'Valenciennes FC': 107, 'Verein für Bewegungsspiele Stuttgart 1893': 108, 'Verein für Leibesübungen Bochum 1848 Fußballgemeinschaft': 109, 'Verein für Leibesübungen Wolfsburg': 110, 'Villarreal Club de Fútbol S.A.D.': 111, 'Vitesse Arnhem': 112, 'West Ham United Football Club': 113, 'Wolverhampton Wanderers Football Club': 114}

Mapping for 'domestic_competition_id' column:
{'ES1': 0, 'FR1': 1, 'GB1': 2, 'IT1': 3, 'L1': 4, 'NL1': 5, 'RU1': 6, 'SC1': 7}

Mapping for 'stadium_name' column:
{'AFAS Stadion': 0, 'AMEX Stadium': 1, 'Abanca Balaídos': 2, 'Abe Lenstra Stadion': 3, 'Alberto Picco': 4, 'Allianz Arena': 5, 'Allianz Riviera': 6, 'Allianz Stadium': 7, 'Anfield': 8, 'Arechi': 9, 'Arsenal': 10, 'Artemio Franchi': 11, 'BayArena': 12, 'Benito Villamarín': 13, 'Bluenergy Stadium': 14, 'Brianteo': 15, 'Cambuurstadion': 16, 'Carlo Castellani': 17, 'Coliseum': 18, 'Craven Cottage': 19, 'De Adelaarshorst': 20, 'De Grolsch Veste': 21, 'De Oude Meerdijk': 22, 'Decathlon Arena-Stade Pierre-Mauroy': 23, 'Deutsche Bank Park': 24, 'Diego Armando Maradona': 25, 'El Sadar': 26, 'Elland Road': 27, 'Estadio de Vallecas': 28, 'Etihad Stadium': 29, 'Ettore Giardiniero': 30, 'Euroborg': 31, 'Europa-Park Stadion': 32, 'Fortuna Sittard Stadion': 33, 'GelreDome': 34, 'Gewiss Stadium': 35, 'Giovanni Zini': 36, 'Giuseppe Meazza': 37, 'Goffertstadion': 38, 'Goodison Park': 39, 'Groupama Stadium': 40, 'Gtech Community Stadium': 41, 'Ibrox Stadium': 42, 'Johan Cruijff ArenA': 43, 'José Zorrilla': 44, 'King Power Stadium': 45, 'Kras Stadion': 46, 'La Cerámica': 47, 'London Stadium': 48, 'Luigi Ferraris': 49, 'MHPArena Stuttgart': 50, 'Mallorca Son Moix': 51, 'Mandemakers Stadion': 52, 'Manuel Martínez Valero': 53, 'Mapei Stadium - Città del Tricolore': 54, 'Marcantonio Bentegodi': 55, 'Mestalla': 56, 'Mewa Arena': 57, 'Molineux Stadium': 58, 'Montilivi': 59, 'Nuevo Mirandilla': 60, 'Old Trafford': 61, 'Olimpico Grande Torino': 62, 'Olimpico di Roma': 63, 'Olympiastadion Berlin': 64, 'Olímpic Lluís Companys': 65, 'Orange Vélodrome': 66, 'Parc des Princes': 67, 'Philips Stadion': 68, 'Power Horse Stadium': 69, 'PreZero Arena': 70, 'RCDE Stadium': 71, 'Ramón Sánchez-Pizjuán': 72, 'Reale Arena': 73, 'Red Bull Arena': 74, 'RheinEnergieSTADION': 75, 'Riyadh Air Metropolitano': 76, 'SIGNAL IDUNA PARK': 77, 'San Mamés': 78, 'Santiago Bernabéu': 79, 'Selhurst Park': 80, 'Sparta-stadion - Het Kasteel': 81, "St James' Park": 82, "St Mary's Stadium": 83, 'Stade Auguste-Delaune': 84, 'Stade Bollaert-Delelis': 85, 'Stade Francis-Le Blé': 86, 'Stade François-Coty': 87, 'Stade Gabriel-Montpied': 88, 'Stade Louis-II': 89, "Stade de l'Abbé-Deschamps": 90, "Stade de l'Aube": 91, 'Stade de la Beaujoire': 92, 'Stade de la Meinau': 93, 'Stade de la Mosson': 94, 'Stade du Hainaut': 95, 'Stade du Moustoir': 96, 'Stadio Renato Dall’Ara': 97, 'Stadion "Galgenwaard"': 98, 'Stadion An der Alten Försterei': 99, 'Stadion Feyenoord "De Kuip"': 100, 'Stadion im Borussia-Park': 101, 'Stadium Municipal': 102, 'Stamford Bridge': 103, 'The City Ground': 104, 'Tottenham Hotspur Stadium': 105, 'Van Donge & De Roo Stadion - Woudestein': 106, 'Veltins-Arena': 107, 'Villa Park': 108, 'Vitality Stadium': 109, 'Volkswagen Arena': 110, 'Vonovia Ruhrstadion': 111, 'WWK ARENA': 112, 'Weserstadion': 113}

In [14]:
print(clubs_df[['net_transfer_record']].head())

  net_transfer_record
0            €-64.65m
1            €-30.60m
2            €-21.50m
3             +€5.80m
4             €-7.10m

In [15]:
# Function to clean and convert the net_transfer_record values
def clean_and_convert(value):
    # Check if the value is a string
    if isinstance(value, str):
        # Remove the Euro sign and spaces
        value = value.replace('€', '').replace(' ', '')

        # Handle '+' and '-' signs if they appear together ('+-')
        if '+-' in value:
            value = '0'  # If it's '+-0', treat it as 0

        # Handle 'm' for millions and 'k' for thousands
        if 'm' in value:
            return float(value.replace('m', '')) * 1e6  # Convert millions to float
        elif 'k' in value:
            return float(value.replace('k', '')) * 1e3  # Convert thousands to float
        else:
            return float(value)  # If there's no suffix, just convert to float
    return value  # If the value is already numeric, return as is

# Apply the function to clean the 'net_transfer_record (€) (m) (k)' column
clubs_df['net_transfer_record'] = clubs_df['net_transfer_record'].apply(clean_and_convert)

# Verify the transformation and the updated column name
print(clubs_df[['net_transfer_record']].head())

   net_transfer_record
0          -64650000.0
1          -30600000.0
2          -21500000.0
3            5800000.0
4           -7100000.0

In [16]:
# Select columns with object or category data types (categorical columns)
categorical_columns = clubs_df.select_dtypes(include=['object', 'category'])

print(clubs_df.columns.tolist())

# Display the names of categorical columns
print(categorical_columns.columns.tolist())

['id', 'club', 'season', 'matches_played', 'wins', 'draws', 'losses', 'goals_scored', 'goals_conceded', 'goal_difference', 'points', 'top_scorer', 'clean_sheets', 'possession (%)', 'pass_accuracy (%)', 'shots_per_match', 'fouls_committed', 'yellow_cards', 'red_cards', 'total_injuries', 'recruited_players', 'total_attacks_left', 'total_attacks_middle', 'total_attacks_right', 'conceded_attacks_left', 'conceded_attacks_middle', 'conceded_attacks_right', 'league', 'possession(%)', 'club_standardized_x', 'matched_club', 'club_id', 'club_code', 'name', 'domestic_competition_id', 'squad_size', 'average_age', 'foreigners_number', 'foreigners_percentage', 'national_team_players', 'stadium_name', 'stadium_seats', 'net_transfer_record', 'last_season']
['club']

**Data normalization:**

In [18]:

numerical_columns = clubs_df.select_dtypes(include=['number']).columns.tolist()

# Initialize Min-Max Scaler
scaler = MinMaxScaler()

# Apply Min-Max Scaler to the numerical columns in players_df
clubs_df[numerical_columns] = scaler.fit_transform(clubs_df[numerical_columns])

# Verify the transformation
clubs_df.head()

,id,club,season,matches_played,wins,draws,losses,goals_scored,goals_conceded,goal_difference,...,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,last_season
0,0.000000,Bayern Munich,0.0,0.0,0.72,0.416667,0.115385,0.971831,0.295082,0.937500,...,0.571429,0.722222,0.744186,0.517241,0.558455,0.772727,0.044248,0.917300,0.545308,1.0
1,0.052632,Borussia Dortmund,0.0,0.0,0.76,0.166667,0.192308,0.845070,0.393443,0.803571,...,0.571429,0.777778,0.453488,0.482759,0.478079,0.818182,0.681416,1.000000,0.657628,1.0
2,0.105263,RB Leipzig,0.0,0.0,0.68,0.250000,0.230769,0.577465,0.344262,0.660714,...,0.571429,0.722222,0.441860,0.655172,0.719207,0.772727,0.654867,0.554395,0.687646,1.0
3,0.157895,Union Berlin,0.0,0.0,0.60,0.416667,0.230769,0.394366,0.295082,0.571429,...,0.571429,0.750000,0.732558,0.517241,0.536534,0.272727,0.876106,0.228831,0.777701,1.0
4,0.210526,SC Freiburg,0.0,0.0,0.56,0.416667,0.269231,0.394366,0.393443,0.517857,...,0.571429,0.750000,0.709302,0.413793,0.419624,0.272727,0.283186,0.393685,0.735148,1.0

In [23]:
from google.colab import files
clubs_df.to_csv("clubs_df.csv", index=False)
files.download('clubs_df.csv')